### ISSUE TITLE
Wspólny komponent będący formularzem do dodawania/edycji uczestników

### ISSUE THREAD

**Issue by qiubix** [oaza-waw/rekolekcje-api#28]
Uporządkować komponenty zarządzające uczestnikami: 

- stworzyć pojedynczy komponent zawierający formularz
- stworzyć różne komponenty dla dodawania i edytowania pojedynczego uczestnika, inicjujące ten formularz danymi lub nie

**Comment by wjanaszek** [comment]
Zrobione
